# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/bwl',
                'doc_host': 'https://Fflath.github.io',
                'git_url': 'https://github.com/Fflath/bwl',
                'lib_path': 'bwl'},
  'syms': {'bwl.core': {'bwl.core.foo': ('core.html#foo', 'bwl/core.py')}}}
